// ════════════════════════════════════════════════════════════════════
// Nomad Master 도시 가이드 데이터 (17 cities)
// 각 도시는 유연한 sections 배열로 구성
//
// SECTION TYPES:
//   { type:'divider', label:'PLACES · 가볼 곳' }
//   { type:'places', title, icon, items:[{name, price?, desc}] }
//   { type:'neighborhoods', title, icon, items:[{name, stars, desc}] }
//   { type:'table', title, icon, headers:[], rows:[[cell,...]] }
//   { type:'list', title, icon, items:[] }                 // 일반 bullet 리스트
//   { type:'learn', title, icon, items:[{h, body, highlight?}] }
//   { type:'timeline', title, icon, items:[{when, title, text}] }
//   { type:'subsections', title, icon, items:[{h, items:[]}] }  // h4 + ul 그룹
//   { type:'note', icon, color?, title?, body }            // 작은 메모 카드
// ════════════════════════════════════════════════════════════════════

window.NOMAD_CITIES = (function(){

  return {

    // ════════ 7월 · 더블린 ════════
    'nomad-city-dublin': {
      monthLabel: '7월',
      hero: {
        city: '🇮🇪 더블린',
        tagline: 'City of Writers',
        country: '아일랜드 · Ireland',
        dates: '2028.7.10 — 7.23 (14일)',
        weather: '15-20°C · 변덕스러움, 비 잦음',
        visa: '무비자 90일 · 셰겐 외',
        vibe: '작가 · 펍 · 책 · 음악 · 그레이 톤',
        mode: '글 + 위성 60/40',
        quote: '노벨문학상 수상자 4명을 배출한 도시. 작가 누리한테 1년 노마드 중 가장 작가다운 시간.',
        image: null,
        imageAlt: 'Dublin literary streets',
      },
      meaning: [
        '작가 안목 = 예이츠·조이스·베케트·와일드·쇼·셰이머스 히니의 도시',
        '14일 단기 거점 = Booking 아파트호텔 또는 Airbnb 단기 (누리가 직접 찾기로 함)',
        '포르투 슬로우 모드에서 도시 모드로 전환 = 페이스 변동 적응기',
        '7월 = 아일랜드 성수기. 사람·가격 둘 다 피크',
        '분석가 N 콘텐츠 자산 = 문학·언어·정체성 관련 글감',
      ],
      sections: [
        { type:'divider', label:'PLACES · 가볼 곳' },
        { type:'places', title:'랜드마크 · 작가 누리 우선', icon:'landscape', items: [
          { name:'Trinity College + Book of Kells', price:'€18.50-22',
            desc:'9세기 켈트 수도사들이 만든 채색 필사본. <strong>Long Room (구도서관)이 누리한테 진짜 가치</strong> — 65m 볼트 천장, 검은 오크 빔, 대리석 흉상. 세계에서 가장 아름다운 도서관 중 하나. 사전 예약 필수 (성수기 줄 1시간+). 베케트·와일드·스토커가 다닌 캠퍼스.' },
          { name:'Museum of Literature Ireland (MoLI)', price:'€12',
            desc:'<strong>작가 누리 진짜 추천.</strong> 조이스의 율리시스 초판 + 아일랜드 문학사 전체. 1907년 학생회 건물 안. 시간 충분히 잡기.' },
          { name:'National Museum of Ireland · Archaeology', price:'무료',
            desc:'석기시대부터 현재까지 아일랜드 보물. 켈트 황금·바이킹 유물·습지에서 발견된 시신. 디자이너 누리 = 켈트 패턴 자산.' },
          { name:'Kilmainham Gaol', price:'€8',
            desc:'19세기 정치범 감옥. 아일랜드 독립운동의 핵심 장소. 누리 작가 안목 = 정체성 글감. 사전 예약 필수.' },
          { name:'Chester Beatty Library', price:'무료',
            desc:'미국인 수집가의 사적 컬렉션 → 국가 기증. 이슬람·아시아·중세 유럽 필사본. 더블린 캐슬 안. 조용한 보석.' },
          { name:'Dublin Castle', price:'€8',
            desc:'700년 된 성 → 조지안 궁전. 외부·정원은 무료, 내부 투어 €8.' },
          { name:"St. Patrick's Cathedral", price:'€9',
            desc:'아일랜드 최대 성당. 조나단 스위프트 (걸리버 여행기) 묘.' },
        ]},
        { type:'places', title:'숨은 곳 · 작가·디자이너 누리한테', icon:'explore', items: [
          { name:"Marsh's Library", price:'€5',
            desc:'1707년 아일랜드 최초 공공도서관. 시간이 멈춘 듯한 공간. 작가 누리 글 영감.' },
          { name:"Sweny's Pharmacy", price:'기부제',
            desc:'제임스 조이스 율리시스에 나오는 약국. 현재 = 자원봉사자들이 매일 율리시스 낭독회 운영. <strong>작가 누리 무조건 한 번.</strong>' },
          { name:'Hodges Figgis 서점',
            desc:'1768년 설립 (조이스 율리시스에도 언급). 더블린에서 가장 오래된 서점. 4층짜리 책의 천국.' },
          { name:'Iveagh Gardens', price:'무료',
            desc:'"더블린의 비밀 정원". 시내 한복판인데 관광객 모름. 누리 점심·산책·글 작업.' },
          { name:'Stoneybatter 동네',
            desc:'힙스터 동네. 빈티지 숍·카페·로컬 펍. 7월 = Smithfield & Stoneybatter Festival (스트리트 아트·로컬 음식).' },
          { name:'Howth 등대 + 절벽 산책',
            desc:'DART 기차 25분. 어촌마을 + 절벽 트레일 (2-3시간). 일요일 = 해산물 시장. 누리 위성 후보 1.' },
          { name:'Malahide Castle + Gardens', price:'€15',
            desc:'DART 25분. 12세기 성 + 정원. 누리 위성 후보 2.' },
        ]},
        { type:'neighborhoods', title:'동네별 추천 (14일 단기 거점)', icon:'home', items: [
          { name:'Smithfield',         stars:5, desc:'북쪽 시내. 노스 시내 트렌디. 카페·코워킹·로컬 펍. <strong>누리 베스트 추천.</strong>' },
          { name:'Stoneybatter',       stars:5, desc:'힙스터 + 작가·예술가 거주 동네. 카페 풍부. Smithfield 옆.' },
          { name:'Portobello',         stars:4, desc:'운하 옆. 조용 + 카페·식당 좋음. 작가 거주 동네.' },
          { name:'Ranelagh',           stars:4, desc:'남쪽 시내 외곽. 빅토리안 거리. 조용 + 좋은 음식.' },
          { name:'The Liberties',      stars:3, desc:'구도심 + 트렌디. 기네스 옆. 살짝 시끄러움.' },
          { name:'Temple Bar',         stars:2, desc:'관광 중심. 누리 거주 X (시끄러움, 비쌈).' },
          { name:'Grand Canal Dock',   stars:3, desc:'구글·메타 본사 동네. 모던 + 비쌈.' },
        ]},

        { type:'divider', label:'EXPERIENCES · 해볼 것' },
        { type:'places', title:'아이리시 음악 · 작가 누리 필수', icon:'music_note', items: [
          { name:'Traditional Irish Musical Pub Crawl', price:'€20-25',
            desc:'2명 뮤지션이 안내하는 펍 투어. 아이리시 음악 입문에 가장 좋음. Oliver St. John Gogarty\'s에서 시작. 7-9월 매일 저녁 7:30.' },
          { name:'The Cobblestone (Smithfield)',
            desc:'<strong>관광 X · 진짜 아이리시 세션.</strong> 매일 밤 무료 트래드 세션. 누리 동네 안 (Smithfield 거점이면). 작가들 단골.' },
          { name:"O'Donoghue's Pub",
            desc:'The Dubliners (전설적 포크 그룹) 본거지. 매일 밤 트래드 세션.' },
          { name:"Whelan's (Camden Street)",
            desc:'라이브 음악 펍. 인디·포크. <em>P.S. I Love You</em> 영화 배경.' },
        ]},
        { type:'places', title:'문학 투어', icon:'book', items: [
          { name:'Dublin Literary Pub Crawl', price:'€18-20',
            desc:'배우 2명이 조이스·예이츠·베케트·와일드 작품 발췌 + 펍 4곳 투어. 누리 진짜 추천. 2.5시간.' },
          { name:'Bloomsday (6월 16일) — 누리 시기엔 못 봄',
            desc:'조이스 율리시스 기념일. 7월 = 못 보지만 Sweny\'s에서 매일 낭독회는 가능.' },
          { name:'Yeats Country (Sligo) — 1박 위성',
            desc:'예이츠 묘 + 시의 무대. 더블린에서 기차 3시간. 누리 14일 안에 1박 위성 가능.' },
        ]},
        { type:'places', title:'그 외 체험', icon:'attractions', items: [
          { name:'Guinness Storehouse', price:'€30',
            desc:'7층 양조장 박물관 + Gravity Bar 일몰 (도시 360°). 비싸지만 누리 = 한 번. 사전 예약.' },
          { name:'Jameson Distillery', price:'€26',
            desc:'위스키 투어 + 테이스팅. Smithfield 안.' },
          { name:'Phoenix Park', price:'무료',
            desc:'유럽에서 가장 큰 도심 공원 중 하나 (707헥타르). 사슴 야생. 자전거 대여.' },
          { name:'Glasnevin Cemetery + Botanic Gardens', price:'€15 투어',
            desc:'아일랜드 독립운동가들 묘. 누리 = 죽음·정체성 글감.' },
        ]},

        { type:'divider', label:'LEARN · 배울 것' },
        { type:'learn', title:'누리 디자이너·작가 안목에서 가져갈 것', icon:'school', items: [
          { h:'1. 작가의 도시 = 글의 도시',
            body:'노벨문학상 4명 (예이츠·쇼·베케트·셰이머스 히니) + 율리시스의 조이스 + 드라큘라의 스토커. 인구 130만 도시가 어떻게 세계 문학사 거장을 이렇게 많이 배출했는지 = <strong>아일랜드 정체성 + 영국 식민 + 카톨릭 + 가난 + 언어 (게일어 vs 영어)의 충돌</strong>이 만든 압력. 누리 분석가 N 콘텐츠 자산.' },
          { h:'2. 언어와 정체성',
            body:'아일랜드 = 영어가 모국어이지만 게일어 (Irish)가 공식 언어 1번. 표지판·정부 문서·학교 = 둘 다 표기. 정체성과 언어의 관계 = 누리 한국어·영어 정체성에 비춰 글감.' },
          { h:'3. 펍 = 사회 인프라',
            body:'아일랜드 펍 = 술 마시는 곳 X. <strong>커뮤니티 거실.</strong> 가족·아이·노인 다 옴. 음악·이야기·만남이 일상. 한국 카페 + 한국 술집 + 한국 동네 마실 = 한 곳에 다 있음. 사회 디자인 케이스 스터디.' },
          { h:'4. 켈트 패턴 = 디자이너 자산',
            body:'Book of Kells의 인터레이스 패턴 + 켈트 매듭 + 황금 장식 = 디자이너 누리 본업 자산. 사진 모으기 + National Museum 찬찬히.' },
          { h:'5. 그레이 톤의 미학',
            body:'더블린 = 1년 중 200일 비. 회색 하늘이 일상. <strong>한국 컬러풀 패션과 다른 미학.</strong> 모직·트위드·차분한 톤. 누리 본업 (니트) 자산.' },
        ]},

        { type:'divider', label:'NOMAD MODE · 노마드로서' },
        { type:'places', title:'코워킹 · 14일 단기 시 데이패스 추천', icon:'work', items: [
          { name:'Dogpatch Labs (CHQ Building)', price:'데일리 €25 · 주 €100',
            desc:'테크 중심. 강변. 누리 14일이면 주간권으로 충분.' },
          { name:'WeWork (Charlemont · Iveagh Court · 등)', price:'데일리 €30 · 월 €350+',
            desc:'고급. 비쌈. 짧은 체류면 비추.' },
          { name:'Bank of Ireland Workbench', price:'무료',
            desc:'은행 지점 일부에 무료 코워킹 공간. Wi-Fi + 책상. Grand Canal · Camden · 외 몇 곳. <strong>노마드 진짜 꿀팁.</strong>' },
          { name:'Iconic Offices (다지점)', price:'데일리 €20-30',
            desc:'아일랜드 로컬 체인. Grand Canal·Stephens Green 등.' },
        ]},
        { type:'places', title:'카페 · 작가 누리 작업 베스트', icon:'local_cafe', items: [
          { name:'Third Space (Smithfield)',   price:'€4-5', desc:'노마드 다수. 빠른 Wi-Fi. 누리 동네 안.' },
          { name:'Social Fabric Cafe (Smithfield)', price:'€4-5', desc:'소셜 엔터프라이즈 카페. 조용한 작업 공간.' },
          { name:'Accents Cafe (시내 중심)',     price:'€4-5', desc:'3층짜리 카페. 위층 = 조용한 작업 공간.' },
          { name:'The Library Bar (Central Hotel)', desc:'호텔 안 라이브러리 바. 책 가득 + 안락의자. 오후 작업 + 칵테일.' },
          { name:'3FE Coffee', price:'€4', desc:'더블린 스페셜티 커피 본가. 여러 지점.' },
        ]},
        { type:'places', title:'도서관 · 무료 작업', icon:'menu_book', items: [
          { name:'Dublin City Library + Archive (Pearse St)', price:'무료',
            desc:'중앙 도서관. 조용 + Wi-Fi.' },
          { name:'National Library of Ireland', price:'무료',
            desc:'방문자 카드 발급 후 사용. 작가 누리 = 도서관 작업 자체가 영감.' },
        ]},
        { type:'list', title:'작업 페이스 (누리 14일 모드)', icon:'schedule', items: [
          '<strong>평일 오전</strong> · 4시간 글 작업 (카페·도서관 1곳 고정)',
          '<strong>평일 오후</strong> · 도시 흡수 (월 = 트리니티, 화 = 박물관, 수 = 코딩, 목 = 문학투어, 금 = Stoneybatter)',
          '<strong>토</strong> · Howth 위성 (당일)',
          '<strong>일</strong> · 휴식 + 더블린 동네 산책',
          '<strong>중간 1박</strong> · Sligo (예이츠 컨트리) 또는 위클로 산',
        ]},

        { type:'divider', label:'PEOPLE · 사람 만나는 루트' },
        { type:'subsections', title:'커뮤니티 · 그룹', icon:'groups', items: [
          { h:'페이스북 그룹', items: [
            '<strong>Expats Living in Dublin</strong>',
            '<strong>Dublin Digital Nomads</strong>',
            '<strong>Girl Gone International Dublin</strong> · 여성 한정',
          ]},
          { h:'Meetup.com', items: [
            'Dublin Writers\' Group · 작가 누리 진짜 추천',
            'Dublin Digital Nomads Meetup',
            'Language Exchange (영어 + 게일어 + 외국어)',
          ]},
          { h:'이벤트 (7월 한정)', items: [
            '<strong>Smithfield & Stoneybatter Festival</strong> · 7월 · 동네 페스티벌',
            '<strong>Longitude Festival</strong> · 7월 중순 · 음악 축제 (Marlay Park)',
            '매주 토 · Cow\'s Lane Market (Temple Bar 외곽) · 디자이너·공예가',
          ]},
          { h:'펍 = 자연스러운 만남 루트', items: [
            '아이리시 펍은 혼자 가도 자연스러움. 바에 앉으면 자동으로 대화 시작됨.',
            'The Cobblestone, O\'Donoghue\'s = 진짜 로컬.',
          ]},
        ]},
        { type:'timeline', title:'14일 동안 사람 만나는 루트', icon:'timeline', items: [
          { when:'1-3일차',   title:'동네 정착 + Cobblestone 1번', text:'거점 동네 카페 단골 만들기 + The Cobblestone 트래드 세션 1번' },
          { when:'4-7일차',   title:'Dublin Literary Pub Crawl + Writers\' Group', text:'문학 펍 크롤 + Meetup Writers\' Group 한 번' },
          { when:'8-11일차',  title:'Smithfield Festival + Sweny\'s 낭독회', text:'동네 페스티벌 + 율리시스 낭독회' },
          { when:'12-14일차', title:'깊은 만남 1-2명 유지', text:'골웨이 가기 전 마지막 만남' },
        ]},

        { type:'divider', label:'BUDGET · 가격 종합' },
        { type:'table', title:'14일 비용 분해 (숙소 제외)', icon:'payments',
          headers:['카테고리','세부','14일 합계 (€)','₩'],
          rows: [
            ['<strong>식비</strong>',         '슈퍼 + 가끔 외식 (펍 음식)',           '200-280',  '30-42만'],
            ['<strong>교통</strong>',         'Leap Card (대중교통) 14일',           '35-50',    '5-7만'],
            ['<strong>체험</strong>',         '트리니티+박물관+투어+위성',           '120-180',  '18-27만'],
            ['<strong>펍·음악</strong>',      '주 2-3회 트래드 세션 + 음료',         '80-120',   '12-18만'],
            ['<strong>코워킹/카페</strong>',   '주 2-3회 데이패스 또는 카페',          '60-100',   '9-15만'],
          ],
          footer: ['<strong>14일 합계 (숙소 제외)</strong>', '', '<strong>495-730</strong>', '<strong>74-109만</strong>'],
          note: '박힌 7월 생활비 ₩176만 (더블린+골웨이 합쳐) → 더블린 14일분 ₩88만 라인. OK 안에 들어옴.' },
        { type:'list', title:'가격 짚을 거', icon:'savings', items: [
          '<strong>더블린 7월 = 1년 중 가장 비쌈.</strong> 1월 대비 +30%.',
          '<strong>식비:</strong> 슈퍼 (Tesco, Dunnes, Aldi) = 한국과 비슷, 외식 = 한국 1.5-2배',
          '<strong>펍 음료:</strong> 기네스 1파인트 €6-8, 위스키 €8-12',
          '<strong>커피:</strong> €3.50-4.50',
          '<strong>박물관 다수 = 무료</strong> (National Museum 시리즈)',
          '<strong>Leap Card:</strong> 종이 티켓보다 30% 저렴 (대중교통 카드)',
        ]},

        { type:'divider', label:'FOCUS · 핵심 짚을 것' },
        { type:'learn', title:'다른 도시와 다른 것 · 누리 진짜 챙길 거', icon:'priority_high', items: [
          { h:'1. 7월 = 성수기 = 사전 예약 필수',
            body:'Book of Kells, Kilmainham Gaol, Guinness, Literary Pub Crawl 모두 사전 예약. 안 하면 1시간+ 줄.' },
          { h:'2. 비 대응 = 노마드 필수',
            body:'아일랜드 = 하루에 4계절. 1년 200일 비. <strong>방수 재킷 무조건 챙기기.</strong> 우산보다 후드 재킷이 실용적 (바람).' },
          { h:'3. Sweny\'s Pharmacy 율리시스 낭독회 = 1순위',
            body:'매일 자원봉사자들이 운영. 무료 (기부제). 작가 누리한테 = 작가 신성한 장소. 한 시간 앉아 있기만 해도 글 영감.' },
          { h:'4. 펍 문화 = 진짜 로컬은 Smithfield · Stoneybatter · Camden Street',
            body:'Temple Bar = 관광 펍. 사진만 찍고 음식·음료는 다른 동네에서. The Cobblestone, O\'Donoghue\'s = 진짜 아이리시 음악.' },
          { h:'5. 14일 안에 골웨이 적응 준비',
            body:'더블린 (큰 도시) → 골웨이 (작은 해안 도시) 전환. 마지막 3-4일은 페이스 살짝 늦추기. 더블린 14일 후반 = 글 작업 풀가동, 관광 X.' },
          { h:'6. 안전 = 1티어, 단 시내 중심 늦은 밤 주의',
            body:'O\'Connell Street·Temple Bar 새벽 시간 = 취객 많음. 누리 동네 (Smithfield·Stoneybatter) 안은 안전. 늦은 시간 = 택시 (Free Now 앱).' },
          { h:'7. 작가 누리한테 = 1년 노마드 중 가장 작가다운 14일',
            body:'다른 도시들이 미술·디자인·자연·라이프스타일 중심이라면, 더블린 14일 = 오롯이 글의 도시. 분석가 N 콘텐츠 자산을 가장 많이 쌓을 시간.',
            highlight:'매일 글감 한 줄씩 메모하는 습관 박기.' },
        ]},
      ],
    },

    // ════════ 7월 · 골웨이 ════════
    'nomad-city-galway': {
      monthLabel: '7월',
      hero: {
        city: '🇮🇪 골웨이',
        tagline: 'Home of Aran Knits',
        country: '아일랜드 · Ireland',
        dates: '2028.7.23 — 8.6 (14일)',
        weather: '14-19°C · 대서양 바람, 변덕',
        visa: '무비자 90일 · 셰겐 외',
        vibe: '해안 · 보헤미안 · 음악 · 니트',
        mode: '글 + 위성 60/40',
        quote: '아란 니트 = 본업 디자이너 누리의 진짜 ROI. 1년 노마드 중 가장 본업 자산 쌓을 도시.',
        image: null,
      },
      meaning: [
        '<strong>본업 자산 1순위:</strong> 아란 니트 = 누리 MLB 니트팀 5년차 본업과 직결. 본가 격.',
        '아란 제도 위성 2박 = 진짜 아란 니트 원산지 직접 경험',
        '모헤어 절벽 당일 = 1년 노마드 자연 베스트 중 하나',
        '더블린 (도시 모드) → 골웨이 (소도시 + 자연) 전환',
        '아일랜드 = 게일어 살아있는 마지막 지역 (Gaeltacht)',
      ],
      sections: [
        { type:'divider', label:'PLACES · 가볼 곳' },
        { type:'places', title:'골웨이 시내 랜드마크', icon:'landscape', items: [
          { name:'Latin Quarter (Quay St · Shop St)', desc:'중세 골목 + 컬러풀 가게. 거리 음악가 (busker) 풍부. 누리 산책·아이쇼핑.' },
          { name:'Galway Cathedral', price:'기부제', desc:'1965년 완공된 르네상스+고딕 혼합. 모자이크 천장.' },
          { name:'Spanish Arch + Long Walk', desc:'16세기 스페인 무역 흔적. 강 옆 빨간 row house = 골웨이 시그니처 사진.' },
          { name:'Galway City Museum', price:'무료', desc:'아란 니트·켈트·도시 역사. 스패니시 아치 옆.' },
          { name:'Salthill Promenade', desc:'2km 해안 산책로. 끝에서 돌 던지기 = 골웨이 전통. 누리 매일 아침 산책 후보.' },
          { name:'NUI Galway 캠퍼스', desc:'시 외곽. 강변 + Quadrangle (1849년 빅토리안 건물). 누리 작업 산책.' },
        ]},
        { type:'places', title:'숨은 곳 · 작가·디자이너 누리한테 진짜 좋을 곳', icon:'explore', items: [
          { name:"Charlie Byrne's Bookshop (Middle Street, Cornstore)",
            desc:'<strong>아일랜드 최고 독립 서점 (수년 연속 1위).</strong> 10만 권+ 신·중고 혼합. 골웨이 작가 누리 1순위. 작가 사인회·북런치 정기. 카페 겸 작업 공간.' },
          { name:"Kenny's Bookshop (Liosban Business Park)",
            desc:'1940년 시작. 가족 운영 글로벌 문화 기관급. 시내 외곽이지만 작가라면 무조건. 아일랜드 작가 초판·희귀본 풍부.' },
          { name:'Bell Book and Candle (The Small Crane, Sea Rd, West End)',
            desc:'중고책 + 음악 + 아트. Paul Deacy 운영. 희귀 LP·도서. 누리 톤 진짜 맞는 골목 가게.' },
          { name:'An Taibhdhearc (Middle Street)',
            desc:'<strong>아일랜드 국가 게일어 극장.</strong> 1928년 설립. 골웨이 작가 Walter Macken이 디렉터로 일한 곳. 게일어 공연 가끔 영어 자막. 분석가 N 글감.' },
          { name:'Eyre Square (John F. Kennedy Park)',
            desc:'골웨이 중앙 광장. 시내 한복판 잔디밭. 작업 산책 + 사람 구경. 매주 토요일 마켓.' },
          { name:'Galway Market (St. Nicholas Church 옆)', price:'토·일',
            desc:'매주 토·일 (일요일은 여름만). 14세기 교회 옆. 로컬 수공예가·디자이너 직접 만남. <strong>누리 본업 자산 = 아일랜드 로컬 디자이너 직접 견학.</strong>' },
          { name:"Thomas Dillon's Claddagh Gold (Quay St)",
            desc:'1750년 설립. 세계에서 가장 오래된 보석가게. Claddagh Ring 원조. 디자이너 누리 = 아일랜드 디자인 모티프 학습.' },
        ]},
        { type:'places', title:'아란 니트 · 본업 누리 1순위', icon:'checkroom', items: [
          { name:'Aran Sweater Market (Quay St 지점)', price:'€80-300',
            desc:'1892년 설립 (Inis Mór 본점 분점). 4층짜리. 진짜 핸드니트 + 머신니트 다 있음. <strong>본업 누리 자산: 스티치 패턴 사진·구조 분석.</strong>' },
          { name:'Standún (Spiddal, 골웨이에서 20분)',
            desc:'아일랜드 니트 1티어 브랜드. 디자이너 누리 = 본업 동종 업계 직접 견학. Spiddal 동네 자체가 게일어 마을 (Gaeltacht).' },
          { name:"O'Máille (High St)",
            desc:'1938년 설립. <em>조용한 사나이 (The Quiet Man)</em> 영화에 의상 제공. 더 클래식.' },
          { name:'Galway Wool Co-op',
            desc:'현지 양털 → 실 → 스웨터 전 과정 작은 공방. 워크숍 가능 (€60-100).' },
        ]},
        { type:'places', title:'위성 · 14일 안 무조건', icon:'explore', items: [
          { name:'아란 제도 (Aran Islands)', price:'페리 €30 왕복 · 2박 추천',
            desc:'<strong>누리 진짜 자산.</strong> Rossaveal 항에서 페리. 3개 섬 중 <strong>Inis Mór (큰 섬)</strong> 가장 추천. Dún Aengus = 절벽 위 선사 시대 요새. 자전거 대여 (€15/일)로 섬 한 바퀴. 마을 인구 전체가 게일어 모국어. 아란 니트 본점 + 가족 단위 핸드니트 가게들 다수.' },
          { name:'모헤어 절벽 (Cliffs of Moher)', price:'€10 입장',
            desc:'214m 절벽 8km. 아일랜드 최고 자연 관광지. 골웨이에서 1.5시간 (가이드 투어 €60). 누리 = 당일치기 또는 절벽 위 + 보트 크루즈 (€80).' },
          { name:'Connemara 국립공원', price:'무료',
            desc:'아일랜드 서쪽 황량한 산·호수·바다. Kylemore Abbey (€16) = 호수 옆 빅토리안 수도원. 누리 자연 + 사진 + 글감.' },
          { name:'The Burren', price:'무료',
            desc:'석회암 사막 같은 풍경. 모헤어 가는 길에 들름. 야생화·고대 무덤·달 같은 풍경.' },
          { name:'Doolin (전통 음악 마을)', price:'무료',
            desc:'아일랜드 트래드 음악 본가 중 하나. 인구 200명. 매일 밤 펍 세션. 모헤어 가는 길 1박 추천.' },
        ]},
        { type:'neighborhoods', title:'동네별 추천 (14일 거점)', icon:'home', items: [
          { name:'Latin Quarter', stars:5, desc:'시내 중심. 보행자 골목. 카페·펍·니트 가게. <strong>누리 베스트 추천.</strong>' },
          { name:'West End',      stars:4, desc:'강 건너 서쪽. 빈티지·해산물 식당. 조용한 보헤미안.' },
          { name:'Salthill',      stars:4, desc:'해안. 산책로. 시내 도보 25분. 누리 작업·산책 균형.' },
          { name:'Claddagh',      stars:3, desc:'옛 어촌마을. 시내 옆. 강 + 빨간 row house.' },
        ]},

        { type:'divider', label:'EXPERIENCES · 해볼 것' },
        { type:'places', title:'아이리시 음악 · 더블린보다 진짜 로컬', icon:'music_note', items: [
          { name:'The Crane Bar (Sea Rd, West End)',
            desc:'<strong>골웨이 트래드 1순위.</strong> 매일 밤 2층에서 세션. 관광객 X, 진짜 뮤지션들 본거지.' },
          { name:'Tig Cóilí (Mainguard St)', desc:'매일 오후·저녁 트래드 세션. 시내 한복판. 무료.' },
          { name:'Tigh Neachtain (Quay St)', desc:'1894년 시작. 골웨이에서 가장 사랑받는 펍. 매일 음악.' },
          { name:"Monroe's Tavern", desc:'아일랜드 댄스 (set dancing) 가능. 누리 = 직접 춤도.' },
        ]},
        { type:'places', title:'그 외 체험', icon:'attractions', items: [
          { name:'Galway International Arts Festival', price:'€10-50',
            desc:'<strong>7월 중순 (누리 골웨이 시기 정확히 겹침).</strong> 2주간. 연극·서커스·음악·미술. 골웨이 1년 중 가장 화려한 시기.' },
          { name:'Galway Races (Ballybrit)', price:'€25-50',
            desc:'7월 말 7일간 경마 페스티벌. 아일랜드 최대. 모자 패션쇼 + 위스키 + 사람 구경.' },
          { name:'Sheep Sheering 농장 견학', price:'€20-30',
            desc:'누리 본업 자산. 골웨이 외곽 양 농장에서 양털 자르기 → 니트 원료 전 과정 견학.' },
          { name:'아일랜드 게일어 첫 마디 배우기',
            desc:'Gaeltacht 마을 가기 전 (Spiddal·Inis Mór) 기본 인사 배우면 환영 받음. <em>Dia duit</em> (안녕), <em>Go raibh maith agat</em> (감사합니다).' },
        ]},

        { type:'divider', label:'LEARN · 배울 것' },
        { type:'learn', title:'누리 본업 자산 · 디자이너 안목', icon:'school', items: [
          { h:'1. 아란 스티치 = 클랜 식별 시스템',
            body:'아란 스웨터 = 가족·클랜마다 고유 스티치 패턴. 옛날엔 어부가 바다에서 죽어 시신 못 알아볼 때 스웨터 패턴으로 가족 식별. <strong>옷 = 디자인 + 정체성 + 식별 시스템</strong>이 한 옷에 다 박힘.<br><br>· <strong>Cable (꼬임)</strong> = 어부의 밧줄 → 풍어 기원<br>· <strong>Diamond</strong> = 작은 밭 → 부와 성공<br>· <strong>Honeycomb (벌집)</strong> = 일벌 → 행운<br>· <strong>Zig Zag</strong> = 절벽 길<br>· <strong>Tree of Life</strong> = 가족 결속·장수<br>· <strong>Moss (이끼)</strong> = 풍요',
            highlight:'누리 MLB 니트 디자인에 적용 가능 · 한국 클랜 (가문) 모티프 + 아란 스티치 = 새 컬렉션 아이디어.' },
          { h:'2. 무지 니트 vs 패턴 니트',
            body:'아란 = 100% 양털 + 자연 라놀린 = 물 빠짐·보온. 1950년대 그레이스 켈리 보그 표지 입은 후 세계화. <strong>기능 → 패션 변화 케이스 스터디.</strong>' },
          { h:'3. 게일어 (Irish) = 죽어가는 언어와 디자인',
            body:'인구 100만 중 모국어 사용자 7만. 정부가 살리려 노력 중. 표지판·정부·학교 = 게일어 우선. 누리 분석가 N = 언어와 정체성·디자인의 관계 글감.' },
          { h:'4. 보헤미안 + 시골 + 음악',
            body:'더블린 (도시) ≠ 골웨이 (소도시 + 자연 + 음악). 진짜 아일랜드는 골웨이·코네마라·아란에 있음.' },
        ]},

        { type:'divider', label:'NOMAD MODE · 노마드로서' },
        { type:'places', title:'코워킹 · 14일 단기', icon:'work', items: [
          { name:'PorterShed (Eyre Square 근처)', price:'데일리 €20 · 주 €80',
            desc:'<strong>골웨이 1순위.</strong> 테크 스타트업 허브 · 골웨이 디지털 노마드 거점. NDRC 액셀러레이터 입주. 빠른 Wi-Fi + 회의실 + 정기 이벤트.' },
          { name:'Platform 94 (Mervue)', price:'데일리 €15 · 월 €180',
            desc:'로컬 코워킹. 조용. 시내 외곽 (버스 15분). 작업 집중용. 누리 = 1주차 짧게.' },
          { name:'Bank of Ireland Workbench (Eyre Sq)', price:'무료 (BoI 고객) · 일회 무료 가능',
            desc:'은행 라운지 코워킹. Eyre Square 한복판. 짧은 작업 + 노트북 + 커피. 5G·콘센트.' },
          { name:'Clayton Hotel Lobby Workspace', price:'커피값',
            desc:'호텔 로비 작업 가능. 비 오는 날 (골웨이 7월 잦음) 대체 작업 공간.' },
        ]},
        { type:'places', title:'카페 · 작업 가능', icon:'local_cafe', items: [
          { name:'Coffeewerk + Press (Quay St)', price:'€4-5', desc:'스페셜티 커피 + 디자인 잡지. 누리 톤 진짜 맞음.' },
          { name:'Urban Grind', price:'€4', desc:'노마드 다수. 빠른 Wi-Fi. 종일 작업 OK.' },
          { name:'Café Temple', price:'€3-4', desc:'자연광 좋음. 작가들 단골.' },
          { name:"Charlie Byrne's Bookshop Cafe", desc:'서점 안 카페. 작가 누리 = 시간 보내기 좋음.' },
        ]},
        { type:'places', title:'도서관 · 무료 작업', icon:'menu_book', items: [
          { name:'Galway City Library (Hynes Building, St Augustine St)', price:'무료',
            desc:'시내 중심. 무료 Wi-Fi · 조용 · 신문·잡지 풍부. <strong>누리 글 작업 강력 추천.</strong> 비 오는 날 베스트.' },
          { name:'James Hardiman Library (NUI Galway 본관)', price:'무료 입장',
            desc:'대학 도서관. 일반 입장 일부 시간 가능. 강변 + 빅토리안 건축. 작가 누리 = 분위기 자체로 글 영감. 1849년 Quadrangle 옆.' },
          { name:'Westside Library (Seamus Quirke Rd)', price:'무료',
            desc:'현대적 분관. 조용 + 콘센트 + Wi-Fi. 누리 동네가 West End이면 도보권.' },
        ]},
        { type:'list', title:'작업 페이스 (누리 14일 모드)', icon:'schedule', items: [
          '<strong>주 1 (1-7일)</strong> · 골웨이 시내 적응 + 글 작업 + Crane Bar 한 번',
          '<strong>주말 (8-9일차)</strong> · 아란 제도 2박 (Inis Mór)',
          '<strong>주 2 (10-12일)</strong> · 골웨이 복귀 + 글 풀가동 + Standún 견학 (Spiddal)',
          '<strong>13일차</strong> · 모헤어 절벽 + Doolin 당일치기',
          '<strong>14일차</strong> · 마무리 + 코펜하겐 짐 준비',
        ]},

        { type:'divider', label:'PEOPLE · 사람 만나는 루트' },
        { type:'subsections', title:'커뮤니티 · 만남', icon:'groups', items: [
          { h:'커뮤니티 · 그룹', items: [
            '<strong>Galway Expats</strong> · 페이스북 · 가장 큰 익스팻 그룹',
            '<strong>Galway Digital Nomads</strong> · 페이스북 · 소규모지만 따뜻함',
            '<strong>Female Digital Nomads Ireland</strong> · 여성 한정 안전 사교',
            '<strong>Connemara Knitters Guild</strong> · 누리 본업 동종 사람들',
            '<strong>Galway Writers Workshop</strong> · 작가 모임 (격주)',
          ]},
          { h:'Meetup.com', items: [
            '"Galway International Connections" · 언어 교환 + 익스팻 · 매주',
            '"Galway Creative Coworking" · 프리랜서·창작자 모임',
            '"Galway Photography Walks" · 도시 사진 산책 (디자이너 누리 자산)',
          ]},
          { h:'코워킹 이벤트', items: [
            'PorterShed = 정기 네트워킹·테크 이벤트 (월 2-3회)',
            'PorterShed 데모 데이 = 골웨이 스타트업 신 직접 관찰',
            '14일 단기지만 멤버십 잡으면 자동 노출',
          ]},
          { h:'이벤트', items: [
            '<strong>Galway International Arts Festival</strong> (7월 중순) · 자동 사람 만남 · 워크숍·공연 후 사교',
            '<strong>Tig Cóilí 트래드 세션</strong> · 매일 · 자연스러운 대화',
            '<strong>Galway Market</strong> (St. Nicholas 옆, 매주 토) · 디자이너·공예가 직접 대화',
            "<strong>Charlie Byrne's 북런치</strong> · 비정기 · 작가 누리 자산",
          ]},
          { h:'골웨이 특유 = 펍에 혼자 가도 자연 어울림', items: [
            '골웨이 = 아일랜드에서도 가장 친근한 도시. 펍 바에 앉으면 자동으로 대화 시작.',
            '더블린보다 진짜 따뜻함. <strong>Tigh Neachtain · Tig Cóilí 바 자리</strong>가 1순위.',
          ]},
        ]},

        { type:'divider', label:'BUDGET · 가격 종합' },
        { type:'table', title:'14일 비용 분해 (숙소 제외)', icon:'payments',
          headers:['카테고리','세부','14일 합계 (€)','₩'],
          rows: [
            ['<strong>식비</strong>',                    '슈퍼 + 외식 (해산물)',                  '180-260', '27-39만'],
            ['<strong>교통</strong>',                    '도보 위주, 버스 가끔',                  '25-40',   '4-6만'],
            ['<strong>아란 2박</strong>',                '페리 €30 + 게스트하우스 €70-100/박',     '170-230', '25-34만'],
            ['<strong>모헤어 + Connemara</strong>',       '가이드 투어 1-2회',                   '100-150', '15-22만'],
            ['<strong>펍·음악·니트 쇼핑</strong>',         '음악 + 본업 자산 쇼핑',                 '100-200', '15-30만'],
          ],
          footer:['<strong>14일 합계 (숙소 제외)</strong>', '', '<strong>575-880</strong>', '<strong>86-131만</strong>'] },

        { type:'divider', label:'FOCUS · 핵심 짚을 것' },
        { type:'learn', title:'다른 도시와 다른 것 · 누리 진짜 챙길 거', icon:'priority_high', items: [
          { h:'1. 본업 자산 1순위 도시 · 사진·메모 풍부',
            body:'한국 MLB 본업 가서 컬렉션 응용 가능. 1년 노마드의 진짜 ROI.',
            highlight:'아란 스티치 패턴 사진 = 100장+ 모으기.' },
          { h:'2. 아란 제도 2박 = 페리 사전 예약',
            body:'7월 = 성수기. 페리 (Aran Island Ferries) 사전 예약 필수.' },
          { h:'3. 아란 스웨터 = 한 벌은 무조건 사기',
            body:'예산: 핸드니트 €200-400, 머신니트 €80-150. 누리 본업 + 1년 노마드 기념품 동시. <strong>Aran Sweater Market 본점 (Inis Mór)에서 사기.</strong>' },
          { h:'4. Galway International Arts Festival = 누리 시기 정확히 겹침',
            body:'7월 중순. 무조건 1-2개 공연 예약. 골웨이 1년 중 가장 풍성한 2주.' },
          { h:'5. 게일어 한 마디 = 환영 큰 차이',
            body:'Gaeltacht 마을 갈 때 <em>Dia duit</em> (안녕) 한 마디면 분위기 다름.' },
          { h:'6. 모헤어 = 절벽 위 + 보트 둘 다 추천',
            body:'절벽 위만 = 보통. 절벽 위 + 보트 크루즈 = 완성. 누리 = 한 번뿐인 경험이니 둘 다.' },
          { h:'7. 8월 코펜하겐 전환 준비',
            body:'골웨이 (느림 · 자연) → 코펜하겐 (도시 · 디자인) 전환. 마지막 2일은 글 작업 풀가동 + 짐 정리. 셰겐 카운트 시작 = 8월부터.' },
        ]},
      ],
    },

    // ════════ 8월 · 코펜하겐 ════════
    'nomad-city-copenhagen': {
      monthLabel: '8월',
      hero: {
        city: '🇩🇰 코펜하겐',
        tagline: 'Where Design Meets Hygge',
        country: '덴마크 · Denmark',
        dates: '2028.8.6 — 8.16 (11일)',
        weather: '18-22°C · 긴 낮, 가끔 비',
        visa: '셰겐 무비자 (11일)',
        vibe: '미니멀 디자인 · 휘게 · 자전거',
        mode: '글 + 관광 60/40',
        quote: '누리 디자이너 안목 = 코펜하겐에서 산세리프처럼 정돈된다. 한국 미니멀 + 덴마크 따뜻함.',
        image: null,
      },
      meaning: [
        '<strong>디자이너 안목 1순위 도시</strong> · Arne Jacobsen, Fritz Hansen, Gubi, Muuto, Hay 다 여기',
        '휘게 (hygge) = 누리 NFJ 베이스와 닮은 정서적 따뜻함',
        '자전거 = 도시 인프라 · 1년 노마드에서 가장 자전거 좋은 도시',
        '11일 단기 · Booking 아파트호텔 또는 Locke 아파트호텔 거점',
        '위성 1박 = Louisiana 미술관 (Humlebæk, 25분 기차)',
      ],
      sections: [
        { type:'divider', label:'PLACES · 가볼 곳' },
        { type:'places', title:'디자인·미술 · 디자이너 누리 1순위', icon:'museum', items: [
          { name:'Designmuseum Danmark', price:'DKK 130 (€17)',
            desc:'<strong>무조건 1번.</strong> Arne Jacobsen 의자·Wegner·Poul Henningsen 조명 등 덴마크 디자인 역사 전체. 새 단장 후 더 좋아짐. <strong>본업 누리 자산.</strong>' },
          { name:'Louisiana Museum of Modern Art (Humlebæk)', price:'DKK 145 + 기차 €15 왕복',
            desc:'<strong>1박 위성 강추.</strong> 25mi 북쪽. 코펜하겐 → Humlebæk 기차 35분. 외레순 해협 절벽 위 + 조각 정원 + 4,000점 컬렉션. 쿠사마 야요이 "Gleaming Lights of the Souls" 영구 전시. 누리 1년 노마드 미술관 베스트.' },
          { name:'SMK · National Gallery of Denmark', price:'무료 (특별전 별도)',
            desc:'7세기 덴마크·국제 미술. 햄머쇼이 (덴마크 모더니즘) 컬렉션이 베스트.' },
          { name:'Ny Carlsberg Glyptotek', price:'DKK 125',
            desc:'고대 + 19세기 덴마크·프랑스 회화. Degas의 발레리나 작은 청동상.' },
          { name:'ARKEN Museum of Modern Art', price:'DKK 130',
            desc:'남쪽. 모던 + 현대 미술. 누리 시간 되면.' },
        ]},
        { type:'places', title:'도시 랜드마크', icon:'landscape', items: [
          { name:'Nyhavn', price:'무료', desc:'17세기 항구 + 컬러풀 row house. 코펜하겐 시그니처 사진.' },
          { name:'Christiansborg Palace 탑', price:'무료', desc:'덴마크 의회 + 왕실 접견실. 탑 무료 (사전 예약).' },
          { name:'Rosenborg Castle + 왕실 보물', price:'DKK 135', desc:'왕실 보물 (보석·왕관). 정원 무료.' },
          { name:'Tivoli Gardens', price:'DKK 175 입장', desc:'1843년 놀이공원. 디즈니랜드의 영감. 누리 야간 산책 + 분위기.' },
          { name:'The Little Mermaid', price:'무료', desc:'한 번 보고 가는 것. 작음. 사진만.' },
        ]},
        { type:'places', title:'숨은 곳', icon:'explore', items: [
          { name:'Black Diamond (Royal Danish Library, Slotsholmen)', price:'무료 입장',
            desc:'<strong>누리 작업 공간 1순위.</strong> 1999년 schmidt hammer lassen 건축. 항구 절벽 끝 검은 화강암 큐브. 덴마크 국립 도서관 + 코펜하겐 대학 도서관 동시. 리딩룸 무료 + 카페 + 전시. 작가 누리 = 매일 가도 됨. 토 15시 가이드 투어 (유료).' },
          { name:'Tortus Copenhagen (Kompagnistræde 23)', price:'워크숍 €350-600',
            desc:'<strong>본업 누리 자산.</strong> Eric Landon (2015 덴마크 디자인 어워드 Craftsman of the Year) 도예 스튜디오. 18세기 마구간 건물. <strong>도예 워크숍 1-2일 (Fluted Stoneware 기법) = 누리 본업 응용 가능.</strong> 사전 예약 필수, 인스타로 신청.' },
          { name:'Superkilen Park (Nørrebro)',
            desc:'덴마크 아티스트 + BIG 건축이 디자인한 도시 공원. 3 구역 (빨강·검정·녹색). 디자이너 누리 도시 디자인 자산.' },
          { name:'Cisternerne', price:'DKK 100',
            desc:'지하 저수조 → 현대미술 공간. 어두운 동굴 + 빛 설치. 매년 다른 작가.' },
          { name:'Christiania (자유도시)',
            desc:'1971년 군대 부지 점거한 자치 마을. 정치·아트·라이프스타일 자산. 사진 금지 구역 주의.' },
          { name:'VM Houses (Ørestad)',
            desc:'Bjarke Ingels 설계 아파트. 외부 보기. 누리 본업 자산.' },
          { name:'Reffen Street Food',
            desc:'옛 조선소 → 푸드 트럭 마을. 누리 외식 친구 만남 베스트.' },
        ]},
        { type:'neighborhoods', title:'동네별 (11일 거점)', icon:'home', items: [
          { name:'Vesterbro',     stars:5, desc:'크리에이티브·빈티지·푸드. Republikken 코워킹. <strong>누리 베스트.</strong>' },
          { name:'Nørrebro',      stars:5, desc:'힙스터·이민 문화·디자인 숍. Superkilen·Jægersborggade·Coffee Collective 본가.' },
          { name:'Indre By',      stars:4, desc:'구시가 중심. Black Diamond 도보. 편리하지만 관광객.' },
          { name:'Christianshavn', stars:4, desc:'운하 + 조용. Christiania 옆. 자전거로 시내 5분.' },
          { name:'Frederiksberg', stars:4, desc:'조용 + 가족 + 공원. Designmuseum 도보. 카페·디자인샵. 누리 작업 모드.' },
          { name:'Østerbro',      stars:3, desc:'로컬·조용·고급. 도시 북쪽. 시내 메트로 5-10분.' },
        ]},

        { type:'divider', label:'EXPERIENCES · 해볼 것' },
        { type:'list', title:'자전거 = 무조건', icon:'directions_bike', items: [
          '코펜하겐 = 세계에서 자전거 가장 좋은 도시. 차보다 자전거 많음.',
          '대여: <strong>Donkey Republic</strong> 앱 (24시 DKK 100, 일주 DKK 350)',
          '자전거 전용 다리: Cykelslangen ("자전거 뱀"), Lille Langebro',
          '운하 따라 + 공원 횡단 = 누리 매일 아침 코스',
        ]},
        { type:'places', title:'음식 · 휘게 체험', icon:'restaurant', items: [
          { name:'Torvehallerne 시장', price:'€10-25',
            desc:'중앙 시장. Smørrebrød (덴마크 오픈 샌드위치) + 커피 + 디자인 식품. 누리 점심 베스트.' },
          { name:'Schønnemann (1877)', price:'€20-35',
            desc:'전통 Smørrebrød. 점심만. 누리 한 번.' },
          { name:'Hart Bageri', price:'€5-10',
            desc:'노마 (3미슐랭) 빵집 파생. 페이스트리 베스트.' },
          { name:'Reffen Street Food', price:'€10-15',
            desc:'캐주얼 푸드 시장. 매일.' },
        ]},
        { type:'places', title:'디자인 쇼핑 · 본업 누리 자산', icon:'storefront', items: [
          { name:'Hay House (Pilestræde 29-31)', desc:'덴마크 모던 디자인 본가. 가구·문구·홈웨어. 누리 무조건.' },
          { name:'Illums Bolighus', desc:'덴마크 디자인 백화점. 4층짜리.' },
          { name:'Stilleben (Nørrebro)', desc:'로컬 디자이너 큐레이션. 작은 스튜디오.' },
          { name:'KLASSIK Moderne Møbelkunst', desc:'빈티지 덴마크 디자인. Wegner·Jacobsen 오리지널.' },
        ]},
        { type:'places', title:'본업 워크숍 · 디자이너 누리 무조건', icon:'brush', items: [
          { name:'Tortus Copenhagen 도예 워크숍', price:'€350-600 · 1-2일',
            desc:'<strong>1순위.</strong> Eric Landon Fluted Stoneware 기법 직접 배움. 누리 본업 (텍스타일 디자인) ↔ 도자 디자인 = 패턴·텍스처 매칭 자산. 신청 = Tortus 인스타·웹사이트. 코펜하겐 시기 미리 예약.' },
          { name:'Woolstock (Vesterbro)', price:'커피값 + 실 별도',
            desc:'<strong>뜨개 카페.</strong> 누리 본업 매칭 1순위. 커피 + 실 + 뜨개 작업. 워크숍 정기 (€40-80, 영문 일부). MLB 니트팀 5년차 → 덴마크 뜨개 신 직접 견학.' },
          { name:'CC Skills (Copenhagen Contemporary)', price:'DKK 1,500-3,000',
            desc:'코펜하겐 컨템포러리 미술관 부속 워크숍. 도예 (How Do I Do Ceramics)·드로잉·글쓰기 6주 코스. 단기 1-2회 클래스도. 11일 일정에는 짧은 클래스만 가능.' },
          { name:'Creative Space · ARTXP', price:'DKK 200-500',
            desc:'단기 1-2시간 도예·주얼리·캔들·뜨개 클래스. 누리 = 빠른 체험. ARTXP는 로컬 작가 매칭 플랫폼.' },
        ]},
        { type:'places', title:'그 외 체험', icon:'attractions', items: [
          { name:'Harbor Bath (Islands Brygge / Kastrup Søbad)', price:'무료',
            desc:'코펜하겐 항구 안 수영장. 도시 인프라 디자인의 정수. 8월 = 수영 가능 시즌. 누리 = 1번 무조건.' },
          { name:'CopenHill (Amager Bakke)', price:'스키 DKK 250 · 입장 DKK 100',
            desc:'BIG 건축 설계. <strong>쓰레기 소각장 위 스키 슬로프 + 등산 트레일.</strong> 누리 디자이너 자산 (도시 인프라 디자인 케이스).' },
          { name:'Kayak Tour (Hej Kajak)', price:'DKK 350',
            desc:'코펜하겐 운하 카약 1.5시간. 도시 다른 각도. 8월 = 베스트 시즌.' },
          { name:'Frederiksberg Have + Søndermarken',
            desc:'두 공원 연결. 무료. 누리 자전거 산책 + 작업 사이 쉼.' },
        ]},
        { type:'table', title:'당일 여행 (코펜하겐 외)', icon:'train',
          headers:['도시','교통','편도','특징'],
          rows: [
            ['<strong>Louisiana (Humlebæk)</strong>',  '기차', '35분 · DKK 70',  '1박 위성 강추 (위에 적힘)'],
            ['<strong>Helsingør (햄릿 성)</strong>',   '기차', '45분 · DKK 100', 'Kronborg Castle + 해양박물관. 셰익스피어 햄릿 배경'],
            ['<strong>Malmö (스웨덴)</strong>',         '기차 (Øresund 다리)', '40분 · SEK 100', '스웨덴 당일. Modernist 건축 · Turning Torso'],
            ['<strong>Lund (스웨덴)</strong>',          '기차', '50분 · SEK 130', '중세 대학 도시. 1145년 대성당'],
            ['<strong>Roskilde</strong>',               '기차', '25분 · DKK 80',  '바이킹 박물관 + 1170년 대성당 (UNESCO)'],
            ['<strong>Frederiksborg Castle</strong>',  '기차', '40분 · DKK 80',  '17세기 르네상스 성 + 호수 + 정원'],
          ],
          note: 'Helsingør + Lund + Malmö 한 번에 묶는 가이드 투어 (€100-150) 있음. 누리 = Malmö 단독 당일 또는 Helsingør 단독 추천.' },

        { type:'divider', label:'LEARN · 배울 것' },
        { type:'learn', title:'디자이너 누리 진짜 자산', icon:'school', items: [
          { h:'1. 덴마크 모더니즘 = 누리 본업 핵심 자산',
            body:'1940-50년대 덴마크 모더니즘 = 미니멀 + 따뜻함 + 기능. Wegner Wishbone Chair, Arne Jacobsen Egg Chair, PH Lamp. <strong>한국 디자이너로서 가장 영향력 큰 시기.</strong> 사진·메모·구조 분석 풍부.' },
          { h:'2. 휘게 (Hygge) = 정서 디자인',
            body:'촛불·따뜻한 조명·따뜻한 음료·편한 사람. "큰 등 절대 안 켜기" = 덴마크 인테리어 룰. 누리 NFJ 베이스 + 디자이너 안목과 가장 잘 맞는 정서 디자인.' },
          { h:'3. 도시 인프라 디자인',
            body:'자전거 전용 다리 + 도시 공원 + 항구 수영 (Harbor Bath) = <strong>시민이 도시 인프라를 사용하는 방식 자체가 디자인.</strong> 누리 분석가 N 자산.' },
          { h:'4. 색·재료 팔레트',
            body:'웜 뉴트럴 (베이지·크림·플라스터) + 미니멀한 세이지·소프트 블루 액센트. <strong>나무·돌·울·면 텍스처.</strong> 한국 컬러풀과 다른 미학.' },
        ]},

        { type:'divider', label:'NOMAD MODE' },
        { type:'places', title:'코워킹 · 11일 단기', icon:'work', items: [
          { name:'Republikken (Vesterbro)', price:'데일리 DKK 250 · 주 DKK 1,000',
            desc:'<strong>누리 1순위.</strong> 크리에이티브 프리랜서 거점. 디자이너·작가·테크 믹스. 정기 이벤트. Vesterbro 거점이면 도보.' },
          { name:'Matrikel1 (시내 중심)', price:'데일리 DKK 200',
            desc:'코펜하겐 가장 큰 코워킹. 모던. 누리 단기 OK.' },
          { name:'Soho House Copenhagen', price:'멤버십만',
            desc:'디자인 신 만남용. 누리 신규 가입은 어렵지만 친구 통해 게스트 1번 가능.' },
          { name:'SOHO Coworking (Nørrebro)', price:'데일리 DKK 200',
            desc:'Soho House와 별개. Nørrebro 거점이면 베스트. 카페 + 작업.' },
        ]},
        { type:'places', title:'카페 · 작업', icon:'local_cafe', items: [
          { name:'Coffee Collective (Jægersborggade 외 4지점)', price:'DKK 50', desc:'스페셜티 커피 본가. Nørrebro Jægersborggade 본점이 누리 톤 베스트.' },
          { name:'Prolog Coffee (Vesterbro)', price:'DKK 50', desc:'미니멀 인테리어. 누리 톤. Republikken 도보.' },
          { name:'Atelier September (Indre By)', desc:'아침·점심·디자인 매거진. 작업하다 점심 OK.' },
          { name:'Democratic Coffee (Krystalgade)', desc:'코펜하겐 시립도서관 옆. 디자이너·학생 단골. 빠른 Wi-Fi.' },
          { name:'La Cabra (Indre By · Aarhus 본점 파생)', desc:'3대륙 로스터리. 미니멀. 자리 많음. 누리 종일 작업 OK.' },
        ]},
        { type:'places', title:'도서관 · 무료 작업', icon:'menu_book', items: [
          { name:'Black Diamond (Royal Danish Library)', price:'무료',
            desc:'<strong>누리 1순위.</strong> 항구 절벽 검은 화강암 큐브. 리딩룸 무료 · 빠른 Wi-Fi · 콘센트 · 항구 뷰. 작가 누리 종일 OK. 카페 + 전시도 같이.' },
          { name:'Copenhagen Main Library (Krystalgade)', price:'무료',
            desc:'시립도서관. 시내 중심. 조용. Democratic Coffee 도보.' },
          { name:'Royal Library Garden (Slotsholmen)',
            desc:'Black Diamond 옆 작은 정원. 무료. 8월 햇볕 좋을 때 야외 작업.' },
        ]},
        { type:'list', title:'작업 페이스 (누리 11일 모드)', icon:'schedule', items: [
          '<strong>주 1 (1-4일)</strong> · Vesterbro 또는 Nørrebro 적응 + Designmuseum + 자전거 시내 익히기',
          '<strong>5-6일차 (주말)</strong> · Louisiana 1박 위성 (Humlebæk)',
          '<strong>7-8일차</strong> · 글 풀가동 (Black Diamond) + Tortus 또는 Woolstock 워크숍',
          '<strong>9일차</strong> · Malmö 또는 Helsingør 당일치기',
          '<strong>10일차</strong> · 디자인 쇼핑 (Hay House + Illums Bolighus) + Reffen 저녁',
          '<strong>11일차</strong> · 짐 정리 + 베르겐 출발 준비',
        ]},

        { type:'divider', label:'PEOPLE' },
        { type:'subsections', title:'커뮤니티 · 그룹', icon:'groups', items: [
          { h:'페이스북 그룹', items: [
            '<strong>Copenhagen Digital Nomads</strong> · 가장 큰 노마드 그룹',
            '<strong>Copenhagen Designers Network</strong> · 디자이너 한정 (본업 누리)',
            '<strong>Female Digital Nomads Copenhagen</strong> · 여성 한정 안전 사교',
            '<strong>Expats in Copenhagen</strong> · 익스팻 일반',
            '<strong>Copenhagen Knitters · Stickkafé</strong> · 뜨개 커뮤니티',
          ]},
          { h:'Meetup.com', items: [
            '"Copenhagen Digital Nomads" · 정기 (월 2-3회)',
            '"Copenhagen Creative Mornings" · 매월 토 아침 무료 강연 + 커피',
            '"Copenhagen Language Exchange" · 매주 화·목',
            '"Copenhagen Designers Meetup" · 누리 본업 매칭',
          ]},
          { h:'코워킹 이벤트', items: [
            'Republikken = 정기 네트워킹·런치 (주 1-2회)',
            'Matrikel1 = 데모 데이·강연',
            '11일 단기지만 멤버십 잡으면 자동 노출',
          ]},
          { h:'이벤트 (8월)', items: [
            '<strong>3 Days of Design</strong> (6월) · 누리 시기 X. <strong>8월 = 차분한 시기 (휴가 시즌 후반).</strong>',
            '<strong>Copenhagen Cooking & Food Festival</strong> (8월 후반) · 누리 시기 일부 겹침',
            '<strong>Reffen Street Food</strong> · 매일 · 자연스러운 만남',
            '<strong>Tortus·Woolstock 워크숍</strong> = 자체가 만남 루트',
            '<strong>매주 일 · Frederiksberg 벼룩시장</strong> · 디자이너·로컬',
          ]},
        ]},
        { type:'timeline', title:'누리한테 자연스러운 사교 루트 (11일 시뮬)', icon:'timeline', items: [
          { when:'1-3일',  title:'코워킹 주 멤버십 + 자전거',         text:'Republikken 주 패스 → 자동 노출. 자전거로 도시 익히기 + 카페 단골 1-2개.' },
          { when:'4-6일',  title:'Tortus 또는 Woolstock 워크숍',    text:'본업 매칭 워크숍 = 같은 톤 사람 자연 만남. Designmuseum 일요일 동행 가능.' },
          { when:'7-9일',  title:'Creative Mornings + Meetup',     text:'토 아침 Creative Mornings 1번 + Female Digital Nomads 1번. 표면 인사.' },
          { when:'10-11일', title:'1-2명과 깊은 만남',                text:'커피·자전거 산책으로 친구 1-2명. 다음 도시 (베르겐) 가도 메시지로 이어짐.' },
        ]},

        { type:'divider', label:'BUDGET' },
        { type:'table', title:'11일 비용 (숙소 제외)', icon:'payments',
          headers:['카테고리','세부','11일 (DKK)','₩'],
          rows: [
            ['식비',         '슈퍼 + 시장 + 외식 가끔',            '1,500-2,200', '30-44만'],
            ['교통',         '자전거 대여 + 가끔 메트로',           '400-600',     '8-12만'],
            ['박물관·체험',   'Designmuseum+Louisiana+기타',       '1,200-1,800', '24-36만'],
            ['코워킹/카페',   '주 1-2회 데이패스',                  '800-1,200',   '16-24만'],
          ],
          footer:['<strong>합계</strong>', '', '<strong>3,900-5,800</strong>', '<strong>78-116만</strong>'],
          note: '코펜하겐 = 1년 노마드 중 가장 비싼 도시 중 하나. 박힌 8월 생활비 안에서 맞춤.' },

        { type:'divider', label:'FOCUS' },
        { type:'learn', title:'핵심', icon:'priority_high', items: [
          { h:'1. 11일 = 타이트, 우선순위 잡기',
            body:'Designmuseum · Louisiana · SMK · 디자인 쇼핑 = 무조건. 나머지 = 선택.' },
          { h:'2. Louisiana 1박 위성',
            body:'당일치기 가능하지만 1박 추천. 미술관 안 카페·해변·일몰까지.' },
          { h:'3. 자전거 = 무조건',
            body:'11일 자전거 대여. 자전거 안 타면 코펜하겐 절반만 봄.' },
          { h:'4. 비싸지만 디자이너 자산 = 무조건 ROI',
            body:'1년 노마드 중 가장 비싼 11일이지만 누리 본업 자산 최대치.' },
          { h:'5. 셰겐 카운트 시작 · 11일',
            body:'8월부터 90일 카운트 시작. 코펜하겐 11일 + 베르겐 8일 = 19일 누적.' },
          { h:'6. 베르겐 전환 준비',
            body:'도시 (디자인) → 자연 (피요르드). 마지막 1일 = 짐 준비, 휴식.' },
        ]},
      ],
    },

    // ════════ 6월 · 포르투 ════════
    'nomad-city-porto': {
      monthLabel: '6월',
      hero: {
        city: '🇵🇹 포르투',
        tagline: 'The Soul of the Douro',
        country: '포르투갈 · Portugal',
        dates: '2028.6.9 — 7.9 (1달)',
        weather: '18-25°C · 맑음, 건조',
        visa: '포르투갈 워홀 (1년 다회)',
        vibe: '구도시 · 강 · 아줄레주 · 슬로우 시티',
        mode: '글 풀가동 · 적응 70%',
        quote: 'Saudade — 그리움과 향수와 사랑과 슬픔이 한 단어. 누리 1년 노마드의 첫 단어.',
        image: null,    // 사진 추가하면 hero 배경으로 (지금은 그라데이션 fallback)
        imageAlt: 'Porto Ribeira at sunset',
      },
      meaning: [
        '1년 노마드의 첫 도시 = 적응 + 페이스 잡기',
        '워홀 베이스캠프 = 1년 동안 3번 돌아올 곳 (6월·10월·11월)',
        '디자이너 안목 = 아줄레주·구도시·미니멀 건축 (Álvaro Siza)',
        '작가 안목 = 강·구도심·골목 = 글감 가득',
        '한국 속도 풀어내는 적응기 = 1년 페이스 결정함',
      ],
      sections: [
        { type:'divider', label:'PLACES · 가볼 곳' },
        { type:'places', title:'랜드마크 · 꼭 가는 곳', icon:'landscape', items: [
          { name:'상 벤투 기차역 (São Bento Station)', price:'무료',
            desc:'20,000장 아줄레주가 벽 전체. 디자이너 누리한테 = 한 시간 그냥 멍 때릴 가치. 역사·해전·일상이 타일에 다 박혀있음.' },
          { name:'리브라리아 렐로 (Livraria Lello)', price:'€8',
            desc:'세계에서 가장 아름다운 서점 중 하나. 누리 = 작가니까 무조건. 신고딕 + 빨간 나선 계단. 입장료는 책 구매 시 차감. 오픈 직후 (9:30) 가야 사람 적음.' },
          { name:'클레리구스 탑 (Torre dos Clérigos)', price:'€8',
            desc:'포르투 한복판 종탑. 240계단. 도시 한눈에.' },
          { name:'돔 루이스 1세 다리 (Ponte Dom Luís I)', price:'무료',
            desc:'에펠 제자가 설계. 위층 = 도보·메트로, 아래층 = 차·도보. 일몰 = 위층에서 강 건너 빌라 노바 데 가이아 쪽 보면서.' },
          { name:'포르투 대성당 (Sé do Porto)', price:'€3',
            desc:'12세기. 광장에서 보는 구도심 전경.' },
        ]},
        { type:'places', title:'숨은 곳 · 디자이너·작가 누리한테 진짜 좋을 곳', icon:'explore', items: [
          { name:'Miguel Bombarda 거리 (Cedofeita)',
            desc:'포르투 갤러리 거리. 동시대 미술관·작은 갤러리·디자인 숍 밀집. <strong>매월 셋째 토요일 = 갤러리 동시 오프닝 (Sábado da Arte).</strong>' },
          { name:'Mercado do Bolhão',
            desc:'재단장한 전통 시장. 누리 = 집밥파니까 여기서 야채·과일·생선·치즈 사는 게 노마드 일상.' },
          { name:'Miradouro da Vitória', price:'무료',
            desc:'무료 전망대. 구도심 + 강 + 빨간 지붕. 관광객 덜함.' },
          { name:'Jardins do Palácio de Cristal',
            desc:'공원 + 도서관 (Biblioteca Municipal Almeida Garrett 안). 누리 작업·산책 둘 다.' },
          { name:'Capela das Almas',
            desc:'외벽 전체 파란 아줄레주. 트램 정거장 옆이라 그냥 지나가다 마주침.' },
          { name:'Foz do Douro (도시 서쪽 끝, 강이 바다 만나는 곳)',
            desc:'1번 트램 (1900년대 빈티지) 타고 가는 길 자체가 경험. 펠게이라스 등대 + 해변 + 카페 + 일몰. 시내에서 자전거 6km (Biclas & Triclas 대여).' },
          { name:'Vila Nova de Gaia (강 건너편)',
            desc:'포트와인 셀러 다 여기. 케이블카 + 강변 산책. 미라도루 다 세하 두 필라르 = 다리 + 도시 전경 베스트.' },
        ]},
        { type:'neighborhoods', title:'동네별 추천 (거점 잡기)', icon:'home', items: [
          { name:'Cedofeita', stars:5, desc:'디자인·예술 동네. Vila Coworking · CRU Cowork · 갤러리 · 카페. <strong>누리 메인 추천.</strong>' },
          { name:'Bonfim',     stars:4, desc:'트렌디·창작자 동네. 카페·부티크. Cedofeita보다 조용.' },
          { name:'Baixa',      stars:3, desc:'구도심 중심. 편하지만 관광객 많음.' },
          { name:'Foz do Douro', stars:3, desc:'바닷가 + 조용. 시내 접근 살짝 멀음.' },
          { name:'Boavista',   stars:3, desc:'비즈니스 + 모던. 카자 다 무지카 옆.' },
          { name:'Ribeira',    stars:2, desc:'강변 미관 베스트, 거주 시 시끄럽고 비쌈.' },
        ]},

        { type:'divider', label:'EXPERIENCES · 해볼 것' },
        { type:'places', title:'아줄레주 페인팅 워크숍 · 디자이너 누리 무조건', icon:'brush', items: [
          { name:'Gazete Azulejos (Bonfim)', price:'€40-55 · 2h',
            desc:'<strong>누리 1순위 추천.</strong> 누리 동네 안. 2장 타일 페인팅. 24시간 후 가마 굽고 픽업. 마리사·알바 듀오 운영.' },
          { name:'Frágil Studio', price:'€45 · 2h',
            desc:'프란시스코 페세게이로 (포르투 본토 도예가). "Tiles and Tea" 워크숍.' },
          { name:'MACS Studio (R. da Boavista 84)', price:'€35 · 2h',
            desc:'10가지 전통 패턴 스텐실 또는 자체 디자인.' },
        ]},
        { type:'places', title:'포트와인 셀러 (Vila Nova de Gaia)', icon:'wine_bar', items: [
          { name:"Taylor's", price:'€25-40', desc:'가장 큰 셀러 중 하나. 정원에서 테이스팅. 영문 가이드.' },
          { name:'Cálem',    price:'€20-35', desc:'치즈·초콜릿 페어링 옵션 강추.' },
          { name:"Graham's", price:'€25-50', desc:'강변 위쪽. 일몰 뷰 좋음.' },
        ]},
        { type:'places', title:'그 외 체험', icon:'attractions', items: [
          { name:'Douro Valley 데이트립', price:'€80-150',
            desc:'기차 또는 가이드 투어로 당일 또는 1박. 와이너리 2-3곳 + 점심. 누리 = 와인 잘 안 마셔도 풍경 자체로 가치 있음 (UNESCO).' },
          { name:'6 다리 크루즈 (Six Bridges)', price:'€15-20 · 50분',
            desc:'라벨로 보트 (전통 와인 운반선). 강에서 보는 도시 다른 각도.' },
          { name:'Casa da Mariquinhas (Ribeira 파두)', price:'€30-50',
            desc:'저녁 식사 + 파두 라이브. 누리 = 음악 + 작가 영감 + 분위기.' },
          { name:'Casa da Música 콘서트', price:'€10-50',
            desc:'렘 콜하스 설계 (디자이너 누리 = 건축으로도 가치). 가이드 투어 €10.' },
        ]},
        { type:'table', title:'당일 여행 (포르투 외)', icon:'train',
          headers:['도시','기차','편도','특징'],
          rows: [
            ['<strong>아베이루 (Aveiro)</strong>',  '1시간', '€4-7', '포르투갈의 베니스 · 컬러풀 보트'],
            ['<strong>기마랑이스</strong>',           '1시간', '€8',   '포르투갈의 발상지 · UNESCO 중세 성'],
            ['<strong>브라가 (Braga)</strong>',       '1시간', '€8',   '종교 중심지 · Bom Jesus 계단'],
            ['<strong>마토지뉴스</strong>',           '30분',  '€3',   '해변 + 해산물 식당'],
          ]},

        { type:'divider', label:'LEARN · 배울 것' },
        { type:'learn', title:'누리 디자이너·작가 안목에서 진짜 가져갈 것', icon:'school', items: [
          { h:'1. 아줄레주의 시스템적 사고',
            body:'13세기 무어인 → 16세기 이탈리아 마욜리카 → 17-18세기 포르투갈식 청백 → 20세기 모던 변주. 패턴 모듈화 (단일 타일 → 반복 → 무한 패턴) = 디자이너 누리 본업 (니트 디자인)과 직결.',
            highlight:'포르투갈은 1개 타일을 200년 동안 변주해서 도시 전체 표면을 디자인함. 누리한테 = 모듈 시스템 사고의 진짜 케이스 스터디.' },
          { h:'2. 슬로우 슬로우',
            body:'점심 2시간, 카페 한 잔 1시간, 거리 산책 1시간. 한국 속도 ≠ 포르투갈 속도. 누리 노마드 첫 도시 = 한국 속도 풀어내는 적응기.' },
          { h:'3. 포르투갈 디자인 = 미니멀 + 디테일',
            body:'Álvaro Siza Vieira (프리츠커 수상자, 세할베스 미술관 설계) + Eduardo Souto de Moura (프리츠커 수상자). 두 명 다 포르투 출신. 누리한테 = 포르투갈 모던 건축 = 한국 미니멀 + 라틴 따뜻함.' },
          { h:"4. 작가 자산 = 도시의 '한 단어'",
            body:'포르투 한 단어 = <em>saudade</em> (사우다드). 그리움 + 향수 + 사랑 + 슬픔이 한 단어. 누리 = 분석가 N으로 글 쓸 때 도시 한 단어를 잡는 습관 = 1년 노마드 콘텐츠 자산.' },
        ]},

        { type:'divider', label:'NOMAD MODE · 노마드로서' },
        { type:'places', title:'코워킹 · 한 달 멤버십 잡으면 좋음', icon:'work', items: [
          { name:'Vila Coworking (Cedofeita)', price:'2026 오픈',
            desc:'<strong>누리한테 1순위 추천 후보.</strong> 1,000m² 정원 + 야외 작업 공간. 누리 도착 시 (2028.6) 이미 자리 잡았을 듯.' },
          { name:'CRU Cowork (Cedofeita)', price:'데일리 €15 · 월 €130-180',
            desc:'디자인·예술·기술 프리랜서 중심. 누리 톤 진짜 맞음.' },
          { name:'Porto i/o (3 지점)', price:'데일리 €15-18 · 월 €140-200',
            desc:'Cedofeita / Vila Nova de Gaia / Centro. 가장 큰 노마드 커뮤니티. 정기 이벤트.' },
          { name:'Typographia Cowork', price:'월 €120-170',
            desc:'클레리구스 탑 근처. 커뮤니티 강함.' },
        ]},
        { type:'places', title:'카페 · 작업 가능, Wi-Fi 좋음', icon:'local_cafe', items: [
          { name:'Combi Coffee Roasters (시내)', price:'€3-4', desc:'스페셜티 커피 · 빠른 Wi-Fi · 디자이너·노마드 다수.' },
          { name:'Mesa 325 (Bonfim)',           price:'€2-3', desc:'넓고 조용. 누리 동네 안.' },
          { name:'Café Candelabro',              price:'€2-3', desc:'서점 겸 카페. <strong>작가 누리한테 진짜 좋음.</strong> 오후 작업.' },
          { name:'Rota do Chá',                  price:'차 €4-6', desc:'찻집. 정원 있는 곳도 있음. 깊은 집중용.' },
          { name:'Café Progresso',               price:'€2', desc:'포르투 가장 오래된 카페 (1899). 글쓰는 사람한테 분위기.' },
        ]},
        { type:'places', title:'도서관 · 무료 작업', icon:'menu_book', items: [
          { name:'Biblioteca Municipal Almeida Garrett', price:'무료',
            desc:'Palácio de Cristal 정원 안. 무료 Wi-Fi · 조용 · 정원 산책. <strong>누리 글 작업 최강.</strong>' },
          { name:'Biblioteca Pública Municipal do Porto', price:'무료',
            desc:'역사적 도서관 · 무료 인터넷.' },
        ]},
        { type:'list', title:'작업 페이스 (누리 모드)', icon:'schedule', items: [
          '<strong>평일 9-13시</strong> · 거점 (Cedofeita 거점 + CRU 또는 Vila Coworking)',
          '<strong>오후 14-17시</strong> · 도시 천천히 흡수',
          '월 = 시내 / 화 = Foz / 수 = 코딩 풀데이 / 목 = 갤러리 / 금 = Vila Nova de Gaia',
          '<strong>주말</strong> · 데이트립 (아베이루·기마랑이스·도우로 밸리)',
        ]},

        { type:'divider', label:'PEOPLE · 사람 만나는 루트' },
        { type:'subsections', title:'커뮤니티 · 그룹', icon:'groups', items: [
          { h:'페이스북 그룹', items:[
            '<strong>Expats Porto</strong> · 가장 큰 익스팻 그룹',
            '<strong>Porto Digital Nomads</strong> · 노마드 한정',
            '<strong>Female Digital Nomads Porto</strong> · 여성 한정 (안전 사교 환경)',
          ]},
          { h:'Meetup.com', items:[
            '"Porto Digital Nomads" 정기 모임 (월 1-2회)',
            '언어 교환 (Language Exchange) · 무료',
            '디자인·아트 워크숍 그룹',
          ]},
          { h:'코워킹 이벤트', items:[
            'Porto i/o = 정기 네트워킹·소셜 (주 1-2회)',
            'Selina Navis = 워크숍·이벤트',
            '누리 = 코워킹 멤버십 잡으면 자연스럽게 합류',
          ]},
          { h:'이벤트', items:[
            '<strong>Cedofeita 갤러리 토요일 (Sábado da Arte)</strong> · 매월 셋째 토요일 · 미겔 봄바르다 거리 동시 오픈 · 와인·작품·사람 자연스럽게',
            '워크숍 자체 = 만남 루트 (아줄레주·도예·요리·와인)',
            'Parque da Cidade 토요일 아침 러닝 그룹 · 무료',
          ]},
        ]},
        { type:'timeline', title:'누리한테 자연스러운 사교 루트 (4주 시뮬)', icon:'timeline', items: [
          { when:'1주차', title:'코워킹 한 달 멤버십', text:'Vila Coworking 또는 Porto i/o → 자동 노출 + 자연스러운 인사' },
          { when:'2주차', title:'아줄레주 워크숍 + 갤러리 토요일', text:'Gazete Azulejos 워크숍 1번 + Cedofeita Sábado da Arte 1번' },
          { when:'3주차', title:'Female Digital Nomads Porto 모임', text:'여성 노마드 한정 안전한 사교 환경' },
          { when:'4주차', title:'1-2명과 깊은 만남 유지', text:'커피·산책으로 표면 인사 → 진짜 친구 1-2명' },
        ]},

        { type:'divider', label:'BUDGET · 가격 종합' },
        { type:'table', title:'1달 비용 분해 (숙소 제외)', icon:'payments',
          headers:['카테고리','세부','월 합계 (€)','₩'],
          rows: [
            ['<strong>식비</strong>',    '시장 + 슈퍼 + 가끔 외식',     '250-350',  '37-52만'],
            ['<strong>교통</strong>',    '월 패스 €30 또는 묶음권',     '30-50',    '4-7만'],
            ['<strong>체험</strong>',    '입장료 + 워크숍 + 데이트립',   '200-300',  '30-45만'],
            ['<strong>코워킹</strong>',  '월 멤버십',                   '130-180',  '19-27만'],
          ],
          footer: ['<strong>1달 합계 (숙소 제외)</strong>', '', '<strong>610-880</strong>', '<strong>90-130만</strong>'],
          note: '박힌 생활비 ₩117만 안에 들어옴. OK.' },

        { type:'divider', label:'FOCUS · 핵심 짚을 것' },
        { type:'learn', title:'다른 도시와 다른 것 · 누리 진짜 챙길 거', icon:'priority_high', items: [
          { h:'1. 첫 도시 = 적응이 최우선',
            body:'글 풀가동 + 도시 천천히 흡수. 첫 주는 일·체험 50/50 (적응). 둘째 주부터 일 70 / 체험 30.' },
          { h:'2. 워홀 베이스캠프 = 짐 일부 두기 OK',
            body:'누리 = 포르투갈에 7월·10월·11월 다시 옴. 1달 거점에서 안 쓰는 짐 = 호스트 협의로 보관 가능한지 확인. 또는 신뢰할 만한 저장소 (€5-15/달).' },
          { h:'3. 아줄레주 = 누리 본업 자산',
            body:'워크숍 1번은 무조건 하기. 패턴 사진 모으기 (도시 곳곳). 한국 가서 본업 (니트 디자인) 응용 가능 = <strong>1년 노마드의 진짜 ROI.</strong>' },
          { h:'4. 영어 OK 라인',
            body:'포르투 = 영어 잘 통함 (특히 시내·코워킹·카페). 시장·로컬 가게에선 살짝 제스처 + 포어 단어 (Obrigada · Bom dia · Por favor). 누리 영어 중급 = 충분.' },
          { h:'5. 안전 = 1티어',
            body:'포르투 = 유럽에서 가장 안전한 도시 중 하나. 밤 산책 OK (Cedofeita·Bonfim 동네 안). 단 시내 중심·관광지에선 소매치기 주의.' },
          { h:'6. 슬로우에 적응하는 게 진짜 일',
            body:'누리 한국 속도 → 포르투갈 속도로 바꾸는 게 첫 도시의 가장 큰 과제. "지금은 천천히 가도 됨" 안 받아들이면 다음 도시들 다 무리 옴.',
            highlight:'이게 1년 노마드 전체의 페이스 결정함.' },
        ]},
      ],
    },

  };
})();
